### ISSUE TITLE
fatal error C1001: Internal compiler error

### ISSUE THREAD

**Issue by v0lt** [team-charls/jpegls-wic-codec#65]
Hello.
I downloaded the jpegls-wic-codec code using git (current commit 374a569). When I try to compile it, I get the error:
```
1>winrt.ixx
1>...\jpegls-wic-codec\build\intermediate\jpegls-wic-codec\x86\Debug\Generated Files\winrt\base.h(5041,71): fatal error C1001: Internal compiler error.
1>(compiler file 'msc1.cpp', line 1603)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>If possible please provide a repro here: https://developercommunity.visualstudio.com
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\CL.exe'
1>    Please choose the Technical Support command on the Visual C++
1>    Help menu, or open the Technical Support help file for more information
1>Done building project "jpegls-wic-codec.vcxproj" -- FAILED.
```
Visual Studio Community 2019 version 16.11.35.

Can you get around this problem?

**Comment by vbaderks** [comment]
Hi,

As stated in the build instructions you need Visual Studio 2022 17.8.0 or newer to compile this project.

VS 2019 claims to support C++20, but it has lots of issues. I reported a couple of them to Microsoft. Most of them are fixed in VS 2022 as Microsoft only fixes security flaws at the moment in VS 2019 as it is in maintenance support mode.
Note: Visual Studio 2022 Community edition can also downloaded for free.
